TARGET = no
TEMPLATE = app
#CONFIG += debug
#DEFINES += MEASURE_PERFORMANCE
CONFIG += c++11
QT += widgets
CXXFLAGS += -Wall
SOURCES += main.cpp
INCLUDEPATH += /home/m5/sw/utility/CurrentWork/include
QMAKE_POST_LINK = "./$$TARGET --test"
